-- Misc
TITLE = 'BallTris'


METER = 64
GRAVITY = 10 * METER

-- Screen
BASE_SCREEN_WIDTH = 640
BASE_SCREEN_HEIGHT = 960
ASPECT_RATIO = 2/3
HOLE_WIDTH = 300
BORDER_THICKNESS = (BASE_SCREEN_WIDTH - HOLE_WIDTH)/2
BOTTOM_THICKNESS = 50

-- Ball
BASE_RADIUS = 25
RADIUS_MULTIPLIERS = {1, 1.7, 2.5}
MAX_RADIUS = BASE_RADIUS * RADIUS_MULTIPLIERS[#RADIUS_MULTIPLIERS]
NUM_COLORS = 5

BALL_SATURATION = 0.6
BALL_VALUE = 1
BALL_HUE_OFFSET = 50

WHITE_BALL_BORDER_COLOR = {99, 99, 99}
WHITE_BALL_BORDER_WIDTH = 5

BALL_DESTROY_TRANSPARENCY = 100

-- Preview
PREVIEW_SPEED = 200
PREVIEW_PADDING = 5

-- Minimum value definitions
FRAMES_TO_STATIC = 30
MIN_SPEED2 = 20

-- Collision
COL_MAIN_CATEGORY = 1

--Input
INPUT_SWITCH_BALL = 'c'
INPUT_RELEASE_BALL = 'space'

-- Game End
MIN_DISTANCE_TO_TOP = 2 * MAX_RADIUS
