METER = 64

-- Screen
SCREEN_WIDTH = 640
SCREEN_HEIGHT = 960
BORDER_THICKNESS = 200
BOTTOM_THICKNESS = 50

-- Ball
BASE_RADIUS = 25
RADIUS_MULTIPLIERS = {1, 1.69, 2.23}
MAX_RADIUS = BASE_RADIUS * 2.23

-- Preview
PREVIEW_SPEED = 200
PREVIEW_PADDING = 5

-- Minimum value definitions
MIN_SPEED2 = 50

-- Collision
COL_MAIN_CATEGORY = 1
